---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    k8s-app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: frontend
  template:
    metadata:
      name: frontend
      labels:
        k8s-app: frontend
    spec:
      containers:
        - name: frontend
          image: hello-devops
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
