name: Build and push
on:
  push:

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: ls project
        run: ls -la /home/runner/work/podman-demo/podman-demo

      - name: ls hello-devops
        run: ls -la /home/runner/work/podman-demo/podman-demo/hello-devops

      ## Replace "docker/build-push-action" with this
      - name: Build image
        id: build-image

        ## Uses buildah to build
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-app
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./hello-devops/Containerfile

      - name: Push to registry
        id: push-to-registry

        ## Redhat push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: robot$devops-demo+ci
          password: TXqUksEa24rJFvesoAQ4cUiHKCexg9jc
          registry: registry.cloud.cbh.kth.se
